const names = [
  "Aubrey ",
  "Audrey ",
  "Austin ",
  "Autumn ",
  "Barbara ",
  "Barry ",
  "Beau ",
  "Benjamin ",
  "Bernard ",
  "Beth ",
  "Caitlin ",
  "Craig ",
  "Cristina ",
  "Crystal ",
  "Curtis ",
  "Cynthia ",
  "Douglas ",
  "Drew ",
  "Duane ",
  "Dustin ",
  "Dwayne ",
  "Dylan ",
  "Ethan ",
  "Eugene ",
  "Eva ",
  "Evan ",
  "Evelyn ",
  "Frances ",
  "Francis ",
  "Francisco ",
  "Frank ",
  "Franklin ",
  "Frederick ",
  "Gloria ",
  "Grace ",
  "Grant ",
  "Gregory ",
  "Guadalupe ",
  "Hollie ",
  "Holly ",
  "Hope ",
  "Howard ",
  "Hunter ",
  "Ian ",
  "India ",
  "Irene ",
  "Isaac ",
  "Isaiah ",
  "Israel ",
  "Julianne ",
  "Julie ",
  "Julio ",
  "Justin ",
  "Justine ",
  "Kristy ",
  "Krystal ",
  "Krystle ",
  "Kurt ",
  "Kyle ",
  "Luis ",
  "Luke ",
  "Lydia ",
  "Lyndsey ",
  "Lynn ",
  "Mitchell ",
  "Molly ",
  "Monica ",
  "Monique ",
  "Morgan ",
  "Nikki ",
  "Nina ",
  "Noah ",
  "Nora ",
  "Norman ",
  "Olivia ",
  "Omar ",
  "Orlando ",
  "Oscar ",
  "Philip ",
  "Phillip ",
  "Preston ",
  "Priscilla ",
  "Quentin ",
  "Quinton ",
  "Ryley ",
  "Richard ",
  "Rinn ",
  "Riptide ",
  "Summer ",
  "Susan ",
  "Suzanne ",
  "Sylvia ",
  "Tristan ",
  "Troy ",
  "Tyler ",
  "Tyrone ",
  "Tyson ",
  "ulger ",
  "unlrich ",
  "unter ",
  "Valerie ",
  "Vanessa ",
  "Vernon ",
  "Veronica ",
  "Victor ",
  "Victoria ",
  "Vincent ",
  "Virginia ",
  "Wade ",
  "Walter ",
  "Warren ",
  "Wayne ",
  "Wendy ",
  "Wesley ",
  "Xavier ",
  "Yolanda ",
  "Yvette ",
  "Yvonne ",
  "Zachary ",
  "Zachery ",
];

let searchinput = document.querySelector(".text");
searchinput.innerText = names;

function clicked(letter) {
  let myfilter = letter;
  let result = names.filter((name) => name.toLowerCase()[0] === myfilter);
  console.log(result);
  searchinput = document.querySelector(".text");
  searchinput.innerText = result + "";
}
function showall() {
  searchinput.innerText = names;
}

// ,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z
